### ISSUE TITLE
admin.nix

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#10]
above all others rules the admin.nix !

**Comment by steveeJ** [comment]
Should we revert parts of #7 and extract packages from _base_ to an _admin_ dependency list?

**Comment by mmaechtel** [comment]
are there any really admin packages in base?

**Comment by steveeJ** [comment]
What exactly is an admin package?

**Comment by mmaechtel** [comment]
Packages, which only we use and not the students ;-)

**Comment by steveeJ** [comment]
I don't think so, so let's close this until we come up with something
