### ISSUE TITLE
ccache: command not found

### ISSUE THREAD

**Issue by nbckr** [htwg-syslab/nix-expressions#110]
In Vorlesung wird `ccache` empfohlen, auf den Lab Containern ist es aber nicht installiert.

**Comment by mmaechtel** [comment]
Installieren? Oder macht das Probleme?

**Comment by mmaechtel** [comment]
Hatte ich letztes Semester aber auch schon empfohlen ....

**Comment by nbckr** [comment]
Es gibt ja kein Paketmanagement wie yum bzw. apt-get in den Lab-Containern, mit dem ich als Übungsteilnehmer unkompliziert Sachen installieren könnte. Mir wurde gesagt, bei fehlenden Paketen solle man in diesem Repo hier ein Issue erstellen.
