### ISSUE TITLE
update rust auf neuste Version

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#118]
Wo ist denn die rustc Version hinterlegt? Habe dazu in den Quellen nix gefunden ...

Im Travis Container läuft bereits die neue Version. Nur für den Fall, dass es dann doch wieder leichte 'Kompatibilitätsprobleme' geben sollte ...

**Comment by steveeJ** [comment]
> Wo ist denn die rustc Version hinterlegt? Habe dazu in den Quellen nix gefunden ...

Stable Rust wird von uns nicht kontrolliert, sondern wird jedes mal beim aufrufen geprüft in den offiziellen Quellen, wo auch rustup nachschaut.

Wenn die `labshell` also jetzt aufgerufen wird kommt die neue Version *"von alleine"*.

**Comment by mmaechtel** [comment]
ok, danke!
