### ISSUE TITLE
shells: PS1/$SHLVL is always 1

### ISSUE THREAD

**Issue by steveeJ** [htwg-syslab/nix-expressions#2]
This is probably due to `--pure` argument to nix-shell which flushes the environment.

**Comment by steveeJ** [comment]
Reported upstream https://github.com/NixOS/nix/issues/1273

**Comment by steveeJ** [comment]
Upstream accepted my PR, now we need to wait for the next release of nix.

**Comment by mmaechtel** [comment]
👍
