### ISSUE TITLE
HOWTO Using nix-shell in bsys

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#23]
- [ ] which workstation is for tests?
- [ ] who needs access to this workstation?
- [ ] small docu about how to use nix-shell environment in bsys.
- [ ] do we need a github-test-grp?

**Comment by mmaechtel** [comment]
Next meeting: Would be Friday 17.3. 17:00 ok? Where?

**Comment by SWW13** [comment]
I have this friday from 14:00 to 19:00 the lecture `Methoden der Gruppenbetreuung`. Maybe before or afterwards?

**Comment by mmaechtel** [comment]
What about 13:15 ? Room: F026

**Comment by SWW13** [comment]
lgtm
