### ISSUE TITLE
shells: PAGER is not set

### ISSUE THREAD

**Issue by steveeJ** [htwg-syslab/nix-expressions#25]
For convenience we should set  `SHELL=less`

**Comment by steveeJ** [comment]
@maechtel would you like to give this a try for practice?

**Comment by mmaechtel** [comment]
which workstation is for tests?

**Comment by steveeJ** [comment]
> @steveeJ which workstation is for tests?

Siehe https://github.com/htwg-syslab/infra-config/issues/14

**Comment by mmaechtel** [comment]
@steveeJ new name of workstation to test?
