### ISSUE TITLE
shell/?: gdb error

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#46]
(gdb) list
1	int main(int argc, char const *argv[])
2	{
3	    int *x = 0;
4	    int y = *x + 1;
5	    return 0;
6	}
(gdb) b 3
Breakpoint 1 at 0x400540: file null.c, line 3.
(gdb) run
Starting program: /home/maechtel/tmp/null
/nix/store/pbs5sfnp9bfv27vz9m7h64w3zgkavfqd-perl-5.22.2/bin/perl: symbol lookup error: /nix/store/pbs5sfnp9bfv27vz9m7h64w3zgkavfqd-perl-5.22.2/bin/perl: undefined symbol: rm
[Inferior 1 (process 2263) exited with code 0177]
(gdb)

**Comment by mmaechtel** [comment]
die Kombi gcc 6.3 mit gdb.unwrapped scheint zu funktionieren ... ??

**Comment by steveeJ** [comment]
Can you try adding the _readline_ pkg to the code dependencies of the shell?

**Comment by mmaechtel** [comment]
hmmm, now it works I cannot reproduce it anymore ... maybe with my next examples, which I will try tomorrow ...

**Comment by mmaechtel** [comment]
#48

**Comment by mmaechtel** [comment]
now i can debug programs compiled with"export hardeningDisable=all" step by step. Couldn't do it without "export hardeningDisable=all"

**Comment by steveeJ** [comment]
I understand that for specific cases, but the symbol lookup error is not explained by optimized code.

**Comment by mmaechtel** [comment]
than I ran into other troubles before ...

**Comment by mmaechtel** [comment]
I meant step-by-step with step=line in code.

**Comment by mmaechtel** [comment]
I had this trouble even when I compiled with -g or -O0 ....

**Comment by steveeJ** [comment]
I think if you passed `-g` and/or `-O0` these are overriden by the gcc wrapper if `hardeningDisable=all` is not set.

I'm confused about the state of this now. Do you still have any issues after setting `hardeningDisable=all`?

**Comment by mmaechtel** [comment]
I'm also confused but with `hardeningDisable=all` I think I had no troubles any more 👍
