### ISSUE TITLE
shells: missing bash completion

### ISSUE THREAD

**Issue by steveeJ** [htwg-syslab/nix-expressions#49]
It would be nice to have bash completion within the shells!

**Comment by mmaechtel** [comment]
and shortcuts to git checkout and friends ....

**Comment by steveeJ** [comment]
@mmaechtel I guess you closed this accidentally? 😆

**Comment by steveeJ** [comment]
> and shortcuts to git checkout and friends ....

I think people should learn to set up their own aliases. The completion is already very helpful for git if it works correctly

**Comment by mmaechtel** [comment]
ups
