### ISSUE TITLE
Mergetool please

### ISSUE THREAD

**Issue by ChK1993** [htwg-syslab/nix-expressions#57]
Is it possible to get a mergetool to make merging the branches more simple?

**Comment by SWW13** [comment]
A GUI merge tool (`git mergetool`) would be nice. I personally like `meld`.

**Comment by steveeJ** [comment]
@SWW13 feel free to file a PR for this one :-)

**Comment by steveeJ** [comment]
Once #61 is merged, `merge.tool` will be set to `vimdiff` upon the next labshell spawn.
