### ISSUE TITLE
Wiki: missing documentation for using this on debian for the syslab courses

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#6]
This is an umbrella issue for tracking the progress of installing and using Nix on our debian workstations and all syslab courses

TODO
- [x] nix installation
- [x] Bootstrap scripts for https://github.com/htwg-syslab/nix-expressions
- [ ] write proper docs

**Comment by mmaechtel** [comment]
Sollen die Docs auf millhouse im Wiki auch hierher?

**Comment by steveeJ** [comment]
Funktion die wir auf den Servern brauchen:

```
labshell () 
{ 
    LABSHELL_PREFETCH_COMMIT=${LABSHELL_PREFETCH_COMMIT:-master};
    LABSHELL_PREFETCH_STDOUT_LOGFILE=/var/tmp/labshell_prefetch_stdout.log;
    LABSHELL_PREFETCH_REPO=${LABSHELL_PREFETCH_REPO:-https://github.com/htwg-syslab/nix-expressions};
    set -x;
    if $(nix-prefetch-url ${LABSHELL_PREFETCH_REPO}/archive/${LABSHELL_PREFETCH_COMMIT}.tar.gz --unpack --print-path > "${LABSHELL_PREFETCH_STDOUT_LOGFILE}.new"); then
        mv ${LABSHELL_PREFETCH_STDOUT_LOGFILE}{.new,};
    fi;
    sh $(sed '2q;d' ${LABSHELL_PREFETCH_STDOUT_LOGFILE})/scripts/remote-labshell.sh $@;
    set +x
}
```

**Comment by mmaechtel** [comment]
Passiert hier noch was oder kann man das issue schliessen?

**Comment by steveeJ** [comment]
@Isele59 ich hatte irgendwo aufgeschrieben wie man von einem leeren Debian anfängt das Template zu erstellen, aber finde es momentan nicht. Hast du das schon aufgeschnappt?

**Comment by Isele59** [comment]
Schau mal in unserem neuen Wiki unter "Template Container", wollte das aber sowieso mal mit Dir durchgehen: https://github.com/htwg-syslab/infra-config/wiki/Template-Container
