### ISSUE TITLE
rustfmt 0.7 VS recent rustfmt 0.83

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#63]
rustfmt on workstation ist quite 'old' .... the recent rustfmt version is 0.83 (on my system)

The results from running these different versions produce different output.

So, I think we need a fast update solution, otherwise we have problems running the ci tests on different systems. Of course I could downgrade, but this only delays the next update problems.

**Comment by steveeJ** [comment]
> So, I think we need a fast update solution, otherwise we have problems running the ci tests on different systems. Of course I could downgrade, but this only delays the next update problems.

I agree that we need an update mechanism, but it should always update to a specified version, not the latest. Because if you always grab the latest version on CI you will have errors without touching a single LOC.

Could we use a _Cargo.lock_ for the shells?

**Comment by mmaechtel** [comment]
yep, thats right! 

I just learned to install specific rust tools via cargo with the --vers Flag.

**Comment by steveeJ** [comment]
> I just learned to install specific rust tools via cargo with the --vers Flag.

I stumbled upon this one too and I think it's enough for this purpose. I think it's not necessary to use a Cargo toml or lock file in this case, but rather specify the crates in the nix code.
