### ISSUE TITLE
Manpage for vmstat is missing .. why?

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#69]
```text
maechtel@ct-bsys-ss17-0 ✓ »shell_bsys@1« ~/rustlab/bsys/homework-sol
$ man vmstat
No manual entry for vmstat
```

**Comment by mmaechtel** [comment]
I thought #68 fixed the path ...

**Comment by mmaechtel** [comment]
the same for 'htop', 'ps' .... seems the fix have del some paths?

**Comment by steveeJ** [comment]
Looks like many packages provide their own packages and don't rely on the big ones that we added in #68.

```
$ sudo find -L /nix/store -name "vmstat.*.gz" 2>/dev/null 
/nix/store/4w4fl4y8y958mpdaym4f2vg5ikwqlwa5-procps-3.3.11/share/man/man8/vmstat.8.gz
```

We could generate a MANPATH that adds one entry per installed package. This way we cover all of them, but rely on `man` to ignore paths that are not there.
