### ISSUE TITLE
shell_base: missing redirections

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#8]
syntastic: error: your shell /nix/store/2vfxa3sg3zl5l9qbvzcyc48hahv8y75a-nixshwrap/bin/nixshwrap can't handle traditional UNIX syntax for redirections
Press ENTER or type command to continue

**Comment by steveeJ** [comment]
Please provide a minimal example for reproducing this.

**Comment by mmaechtel** [comment]
during startup of vim after enabling a lot of plugins ... don't know which one ...

**Comment by mmaechtel** [comment]
syntastic does not work with zsh. Adding 
```
set shell=bash
```
to .vimrc solved the problem

**Comment by steveeJ** [comment]
The script that is referenced in `SHELL` is not compatible with shell scripts. This is not an easy fix, because it requires a single executable that mimics the behavior of a shell and wraps around nix-shell with all the stored settings.
