### ISSUE TITLE
Update Sublime Text in labshell bsys

### ISSUE THREAD

**Issue by dk1088** [htwg-syslab/nix-expressions#84]
@mmaechtel 
Please Update to a new version

**Comment by mmaechtel** [comment]
Do we have one? -> @steveeJ

**Comment by steveeJ** [comment]
We don't control specific versions of packages. We [pinpoint specific revisions for the entire package collection](https://github.com/htwg-syslab/nix-expressions/blob/ca02589ff548d10baeb87d3940021415eaf838e5/default.nix#L7-L14).

**Comment by mmaechtel** [comment]
We have installed sublimetext3-31 -> Sublime Text Build 3126.
```text
$ sublime3 --version
Sublime Text Build 3126
```
I don't have a newer one on my osx running.
You have to start it via 'sublime3' ...

**Comment by steveeJ** [comment]
Ref #53

**Comment by dk1088** [comment]
I have started Sublime with the command "sublime"...
Then it was a mistake on my part. :(
Sorry for this Issue.
[Closed]

**Comment by steveeJ** [comment]
_( @dk1088 it's not actually closed 😆 )_
