### ISSUE TITLE
shells/sysoHW3: binaries for aarch64 are in PATH

### ISSUE THREAD

**Issue by steveeJ** [htwg-syslab/nix-expressions#86]
```
$ which clear
/nix/store/bhyp2vkkzkhd0310n7wf918b1fxv10ml-ncurses-6.0-aarch64-linux-gnu/bin/clear
fagendus@ct-syso-ss17-7 ✓ »sysoHW3@2« ~/SYSO/syso-ss17-grp7/HW3
$ clear
bash: /nix/store/bhyp2vkkzkhd0310n7wf918b1fxv10ml-ncurses-6.0-aarch64-linux-gnu/bin/clear: cannot execute binary file: Exec format error
```

/cc @fabs77

**Comment by fabs77** [comment]
I tried to compile my sysinfo native.
Well compiling and linking seems to work fine, but the execution fails...

`$ ./sysinfo
bash: ./sysinfo: cannot execute binary file: Exec format error
fagendus@ct-syso-ss17-7 ✗ »sysoHW3@2« ~/SYSO/syso-ss17-grp7/HW3/sysinfo
$ file sysinfo
sysinfo: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped, with debug_info
`

Maybe there is another error in the labshell. I guess i will need the native compilation for dropbear too, to have a dropbear instance to generate the ssh key on the host machine.

**Comment by steveeJ** [comment]
> $ ./sysinfo
> bash: ./sysinfo: cannot execute binary file: Exec format error
> fagendus@ct-syso-ss17-7 ✗ »sysoHW3@2« ~/SYSO/syso-ss17-grp7/HW3/sysinfo
> $ file sysinfo
> sysinfo: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped, with debug_info

Is this the whole output for `file`? It's missing the interpreter path!

---

### Workaround

Can you please run the following commands in the labshell and then try to compile natively again? This should also fix the error with the `clear` command.

```bash
unset CC
export PATH=$(echo $PATH | tr ':' '\n' | grep -v aarch64 | tr '\n' ':')
```

**Comment by steveeJ** [comment]
### Labshell Branch with Bugfix

Until the branch with the fix is merged, you can start it manually by passing the URL for it:

```
LABSHELL_EXPRESSIONS_REMOTE_URL=https://github.com/htwg-syslab/nix-expressions/archive/sj-workaround-cross-drawbacks.tar.gz labshell sysoHW3
```
